package client

const (
	AcceptComputeRequest = "/compute-requests/{id}/accept"
	DownloadDataAssetByID = "/data-assets/{id}/download"
	GetDataAssetsByDataModelID = "/data-models/{id}/data-assets"
	CreateAccount = "/accounts"
	RemoveWallet = "/accounts/me/wallets/{address}"
	RefreshToken = "/auth/refresh-token"
	GetComputeRequests = "/compute-requests/me"
	AuthenticateAccount = "/auth"
	GetComputeRequestsReceived = "/compute-requests/received"
	GetDataAssetByID = "/data-assets/{id}"
	UpdateDataAssetByID = "/data-assets/{id}"
	DeleteDataAssetByID = "/data-assets/{id}"
	GetDataModelsByUser = "/data-models/me"
	GetComputeRequest = "/compute-requests/{id}"
	GetCreatedDataAssets = "/data-assets/created"
	GetDataModelByID = "/data-models/{id}"
	UpdateDataModel = "/data-models/{id}"
	GetMyAccount = "/accounts/me"
	UpdateAccount = "/accounts/me"
	AddWallet = "/accounts/me/wallets"
	DeleteAssignedRoleByACL = "/data-assets/{id}/acl/delete"
	GetAllDataAssetsThatTheAuthenticatedUserHasAccessTo = "/data-assets/me"
	GetReceivedDataAssets = "/data-assets/received"
	ShareDataAssetByID = "/data-assets/{id}/share"
	GetAccount = "/accounts/{did}"
	GenerateSignMessage = "/auth/message"
	CreateComputeRequest = "/compute-requests"
	CreateComputingProcess = "/compute-requests/{id}/start"
	CreateANewDataAsset = "/data-assets"
	AssignACLItemsToDataAsset = "/data-assets/{id}/acl"
	UpdateACLItemsToDataAsset = "/data-assets/{id}/acl"
	GetDataModels = "/data-models"
	CreateDataModel = "/data-models"
)

