package common

const (
	UpdateAccount             = "/accounts/me"
	GetMyAccount              = "/accounts/me"
	ShareDataAssetByID        = "/data-assets/{id}/share"
	GetDataModels             = "/data-models"
	CreateDataModel           = "/data-models"
	DownloadDataAssetByID     = "/data-assets/{id}/download"
	CreateAccount             = "/accounts"
	AuthenticateAccount       = "/auth"
	RefreshToken              = "/auth/refresh-token"
	GetMyDataAssets           = "/data-assets/me"
	AssignACLItemsToDataAsset = "/data-assets/{id}/acl"
	UpdateACLItemsToDataAsset = "/data-assets/{id}/acl"
	CreateANewDataAsset       = "/data-assets"
	GetDataAssetByID          = "/data-assets/{id}"
	UpdateDataAssetByID       = "/data-assets/{id}"
	DeleteDataAssetByID       = "/data-assets/{id}"
	GetDataModelsByUser       = "/data-models/me"
	GetDataModelByID          = "/data-models/{id}"
	UpdateDataModel           = "/data-models/{id}"
	GenerateSignMessage       = "/auth/message"
	DeleteAssignedRoleByACL   = "/data-assets/{id}/acl/delete"
)
