package common

const (
	GetDataAssetByID = "/data-assets/{id}"
	UpdateDataAssetByID = "/data-assets/{id}"
	DeleteDataAssetByID = "/data-assets/{id}"
	CreateAccount = "/accounts"
	GetAccount = "/accounts/{did}"
	RefreshToken = "/auth/refresh-token"
	GetDataModelsByUser = "/data-models/me"
	GetDataModelByID = "/data-models/{id}"
	UpdateDataModel = "/data-models/{id}"
	RemoveWallet = "/accounts/me/wallets/{address}"
	GetAllDataAssetsThatTheAuthenticatedUserHasAccessTo = "/data-assets/me"
	AssignACLItemsToDataAsset = "/data-assets/{id}/acl"
	UpdateACLItemsToDataAsset = "/data-assets/{id}/acl"
	ShareDataAssetByID = "/data-assets/{id}/share"
	AddWallet = "/accounts/me/wallets"
	AuthenticateAccount = "/auth"
	CreateANewDataAsset = "/data-assets"
	GetReceivedDataAssets = "/data-assets/received"
	DeleteAssignedRoleByACL = "/data-assets/{id}/acl/delete"
	DownloadDataAssetByID = "/data-assets/{id}/download"
	GetDataModels = "/data-models"
	CreateDataModel = "/data-models"
	GetMyAccount = "/accounts/me"
	UpdateAccount = "/accounts/me"
	GenerateSignMessage = "/auth/message"
	GetCreatedDataAssets = "/data-assets/created"
)

